# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ZRenyinquan\eric6\eric6-21.11\AutoPro_CPy_GUI\AutoPro_CPy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bat.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.text_Welcome = QtWidgets.QTextEdit(self.centralWidget)
        self.text_Welcome.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_Welcome.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_Welcome.setLineWidth(0)
        self.text_Welcome.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_Welcome.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_Welcome.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.text_Welcome.setReadOnly(True)
        self.text_Welcome.setObjectName("text_Welcome")
        self.gridLayout.addWidget(self.text_Welcome, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionSlotSlope = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\ZRenyinquan\\eric6\\eric6-21.11\\AutoPro_CPy_GUI\\images/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSlotSlope.setIcon(icon1)
        self.actionSlotSlope.setObjectName("actionSlotSlope")
        self.actionVI5 = QtWidgets.QAction(MainWindow)
        self.actionVI5.setIcon(icon1)
        self.actionVI5.setObjectName("actionVI5")
        self.actionSlotRes = QtWidgets.QAction(MainWindow)
        self.actionSlotRes.setIcon(icon1)
        self.actionSlotRes.setObjectName("actionSlotRes")
        self.actionPI = QtWidgets.QAction(MainWindow)
        self.actionPI.setIcon(icon1)
        self.actionPI.setObjectName("actionPI")
        self.actionLeakageI = QtWidgets.QAction(MainWindow)
        self.actionLeakageI.setIcon(icon1)
        self.actionLeakageI.setObjectName("actionLeakageI")
        self.actionFreq = QtWidgets.QAction(MainWindow)
        self.actionFreq.setIcon(icon1)
        self.actionFreq.setObjectName("actionFreq")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\ZRenyinquan\\eric6\\eric6-21.11\\AutoPro_CPy_GUI\\images/computer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setIcon(icon1)
        self.actionAbout.setObjectName("actionAbout")
        self.menu.addAction(self.actionSlotRes)
        self.menu.addAction(self.actionSlotSlope)
        self.menu.addAction(self.actionVI5)
        self.menu.addAction(self.actionFreq)
        self.menu.addAction(self.actionPI)
        self.menu.addAction(self.actionLeakageI)
        self.menu.addSeparator()
        self.menu.addAction(self.actionExit)
        self.menu_2.addAction(self.actionAbout)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数据分析软件 V0.1"))
        self.text_Welcome.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; color:#00aa00;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; color:#00aa00;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#00aa00;\">欢迎使用信及公司数据处理软件</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#aa007f;\">AutoPro_CPy</span></p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "功能区"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSlotSlope.setText(_translate("MainWindow", "平板区厚度监控"))
        self.actionVI5.setText(_translate("MainWindow", "伏安特性测试项"))
        self.actionSlotRes.setText(_translate("MainWindow", "平板区电阻分布"))
        self.actionPI.setText(_translate("MainWindow", "正极电流测试项"))
        self.actionLeakageI.setText(_translate("MainWindow", "漏电流测试项"))
        self.actionFreq.setText(_translate("MainWindow", "频率分布测试项"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
        self.actionAbout.setText(_translate("MainWindow", "关于"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
